// Generated by build.mjs — offline support. Version changes whenever any file does.
const CACHE = 'pdfsuite-f52cf90e502a'
const SHELL = ["./","index.html","styles.css","favicon.svg","manifest.webmanifest","pdfsuite.html","icon-192.png","icon-512.png","icon-maskable-512.png","src/pdf/types.js","src/pdf/env.js","src/pdf/crypto.js","src/pdf/filters.js","src/pdf/parse.js","src/pdf/write.js","src/pdf/encodings.js","src/pdf/functions.js","src/pdf/image.js","src/pdf/outline.js","src/pdf/metrics.js","src/zip.js","src/png.js","src/pdf/content.js","src/pdf/ops.js","src/pdf/security.js","src/pdf/stamp.js","src/pdf/redact.js","src/pdf/forms.js","src/pdf/render.js","src/ui/dom.js","src/ui/kit.js","src/ui/catalog.js","src/ui/tool.js","src/ui/pages.js","src/ui/preview.js","src/editor/imagefx.js","src/editor/annots.js","src/editor/view.js","src/editor/signature.js","src/editor/props.js","src/editor/export.js","src/tools/merge.js","src/tools/split.js","src/tools/organize.js","src/tools/rotate.js","src/tools/crop.js","src/tools/edit.js","src/tools/img2pdf.js","src/tools/extract.js","src/tools/pagenum.js","src/tools/watermark.js","src/tools/pdf2img.js","src/tools/pdftext.js","src/tools/compress.js","src/tools/protect.js","src/tools/metadata.js","src/app.js"]
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()))
})
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('pdfsuite-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()))
})
self.addEventListener('fetch', (e) => {
  const req = e.request
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
    if (res.ok && res.type === 'basic') { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)) }
    return res
  }).catch(() => caches.match('index.html'))))
})
